"""Load the synthetic students generated by scripts/generate_fixtures.py.

Phases 2-3 test cross-checking and formatting logic directly against known
field values — no OCR/extraction agent exists yet (that's phase 5). This
module turns each student's ground_truth.json into ExtractedDocument
objects so that code, not a script's ad hoc dict access.
"""

from __future__ import annotations

import json
from datetime import date, datetime
from pathlib import Path

from contracts import ExtractedDocument

REPO_ROOT = Path(__file__).parent
STUDENTS_DIR = REPO_ROOT / "fixtures" / "students"

# The scheme deadline baked into mohammed_irfan's income certificate (which
# expires exactly 11 days before it, per spec section 8). Phases 2-3 have
# no requirement extractor yet, so tests construct a Requirement/RequiredDoc
# by hand against this fixed date rather than parsing a scheme PDF.
SCHEME_DEADLINE = date(2026, 9, 30)


def _parse_date(value: str | None) -> date | None:
    if value is None:
        return None
    return datetime.strptime(value, "%Y-%m-%d").date()


def list_students() -> list[dict]:
    manifest_path = STUDENTS_DIR / "students.json"
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def load_ground_truth(student_id: str) -> dict:
    path = STUDENTS_DIR / student_id / "ground_truth.json"
    return json.loads(path.read_text(encoding="utf-8"))


def student_documents(student_id: str) -> list[ExtractedDocument]:
    """All of a student's documents as ExtractedDocument objects, in the
    fixed order they were generated (marksheet-bearing scenarios rely on
    marksheet appearing first among the certificate types where present)."""
    ground_truth = load_ground_truth(student_id)
    documents = []
    for doc_type, entry in ground_truth["documents"].items():
        documents.append(
            ExtractedDocument(
                doc_type=doc_type,
                source_path=REPO_ROOT / entry["source_path"],
                fields=entry["fields"],
                issue_date=_parse_date(entry["issue_date"]),
                valid_until=_parse_date(entry["valid_until"]),
                extraction_confidence=1.0,  # ground truth, not model-extracted
            )
        )
    return documents


def student_document(student_id: str, doc_type: str) -> ExtractedDocument:
    for doc in student_documents(student_id):
        if doc.doc_type == doc_type:
            return doc
    raise KeyError(f"{student_id} has no {doc_type!r} document")
